/* Ashen Voice Studio v0.7.0 add-on: repo loader, auto director, overrides, SFX */
const OV='ashen-voice-v070-overrides', BASE='/book-data/';
const BUILTIN=[
['wind','Desert Wind','ambience',5],['sand','Sand Hiss','ambience',3],['rumble','Deep Underground Rumble','environment',3.8],['scrape','Stone Scrape','stone',2.2],['impact','Heavy Stone Impact','impact',1.5],['bones','Bones Clatter','impact',1.7],['torch','Torch Crackle','ambience',5],['heartbeat','Heartbeat','body',3],['footsteps','Stone Footsteps','movement',2.5],['rope','Rope Creak','objects',2],['metal','Small Metal Clink','objects',1],['whoosh','Air Whoosh','movement',1.2],['dust','Dust Fall','environment',2.5],['drone','Low Dread Drone','ambience',6],['knock','Stone Knock','impact',.8],['ceramic','Ceramic / Clay Clink','objects',1.2]
].map(([r,name,category,duration])=>({id:'builtin-'+r,name,category,tags:[r,category],source:'builtin',license:'Generated locally',recipe:r,duration}));
let repoSfx=[],baseRender=null,origRenderLine=null,origSaveVoice=null;
const ov=()=>{try{return JSON.parse(localStorage.getItem(OV)||'{"characters":{},"lines":{}}')}catch{return{characters:{},lines:{}}}};
const putOv=o=>localStorage.setItem(OV,JSON.stringify(o));
function sanitize(){state.characters=(state.characters||[]).filter(c=>c?.name&&!/^unknown(?: writer)?$|^unidentified$/i.test(c.name));for(const l of chapter().lines||[]){if(!l.speaker||/^unknown(?: writer)?$|^unidentified$/i.test(l.speaker)){l.speaker='Narrator';l.needsSpeakerReview=true}}}
parseText=function(txt){const blocks=txt.replace(/\r/g,'').split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean),out=[];for(const b of blocks)out.push(makeLine(isQuote(b)?stripOuterQuotes(b):b,'Narrator',isQuote(b)?'dialogue':'narration',isQuote(b)?.2:1,isQuote(b)?'Speaker requires manual assignment':'paragraph'));return out};
function applyOv(){const o=ov();for(const c of state.characters||[])if(o.characters?.[c.name])Object.assign(c,o.characters[c.name]);for(const l of chapter().lines||[]){const x=o.lines?.[l.id];if(!x)continue;if(x.speaker){l.speaker=x.speaker;l.speakerLocked=!!x.speakerLocked}l.directionLocked=!!x.directionLocked;if(x.manualDirection)l.manualDirection=x.manualDirection}}
function rememberChar(c){const o=ov();o.characters[c.name]={mode:c.mode,voice:c.voice,speed:c.speed,pause:c.pause,pitch:c.pitch,tone:c.tone,emotion:c.emotion,intensity:c.intensity,description:c.description,blendA:c.blendA,blendB:c.blendB,blendWeight:c.blendWeight};putOv(o)}
function rememberLine(l){const o=ov();o.lines[l.id]={speaker:l.speaker,speakerLocked:!!l.speakerLocked,directionLocked:!!l.directionLocked,manualDirection:l.manualDirection||null};putOv(o)}
const url=p=>new URL(String(p||'').replace(/^\/+/,''),new URL(BASE,location.origin)).toString();
async function text(p,req=true){if(!p)return null;const r=await fetch(url(p),{cache:'no-store'});if(!r.ok){if(req)throw Error(`${p}: HTTP ${r.status}`);return null}return r.text()}
async function json(p,req=true){const t=await text(p,req);return t==null?null:JSON.parse(t)}
async function loadRepo(noAlert=false){try{setStatus('Loading repository project…');const m=await json('manifest.json');const key=m.activeChapter||Object.keys(m.chapters||{})[0],cfg=m.chapters[key];if(!cfg)throw Error('No active chapter in manifest');const p=await json(cfg.production);if(p?.chapters?.[0]?.lineFiles?.length){const dir=cfg.production.split('/').slice(0,-1).join('/');const chunks=await Promise.all(p.chapters[0].lineFiles.map(f=>json((dir?dir+'/':'')+f)));p.chapters[0].lines=chunks.flat()}state=migrate(p);sanitize();const cards=await json(m.characters,false);if(cards){state.characters=(cards.characters||cards).filter(c=>c?.name&&!/^unknown/i.test(c.name)).map(makeChar)}const man=await text(cfg.manuscript,false);if(man){state.sources=state.sources||{};state.sources.manuscriptText=man}state.dictionary=[];const gp=await text(m.globalPronunciations,false),cp=await text(cfg.pronunciations,false);if(gp)applyPronunciations(gp);if(cp)applyPronunciations(cp);const guide=await text(cfg.guide,false);if(guide){state.guideNotes=guide;state.sources=state.sources||{};state.sources.guideText=guide}const sfx=await json(m.sfxLibrary,false);repoSfx=(sfx?.effects||sfx||[]).map(x=>({...x,source:x.source||'repo'}));state.v7=state.v7||{};state.v7.repo={loaded:true,chapter:key,version:m.version||1,loadedAt:Date.now()};state.v7.sfxCues=state.v7.sfxCues||[];state.v7.customSfx=state.v7.customSfx||[];applyOv();autoDirect(false);save();render();setStatus('Project loaded from repository');return true}catch(e){console.error(e);if(!noAlert)alert('Repository load failed: '+e.message);setStatus('Repository load failed');return false}}
function scene(i,ls){const s=ls.slice(Math.max(0,i-2),i+3).map(x=>x.text).join(' ').toLowerCase();if(/skeleton|dead mouth|throne|journal|compass|zikir ash/.test(s))return'throne / journal';if(/kurash/.test(s)&&/slab|trap|pinned|blood|death|collapsed|scream/.test(s))return'death / shock';if(/treasure|gold|silver|coins|bowl/.test(s))return'treasure / temptation';if(/stair|descent|door|passage|corridor|below/.test(s))return'descent / sealed spaces';return'excavation / discovery'}
function direct(l,i,ls){const sc=scene(i,ls),sp=l.speaker||'Narrator',t=(l.text||'').toLowerCase();let d={label:'measured',scene:sc,emotionPreset:'neutral',speedFactor:1,pitchDelta:0,tone:'neutral',intensity:1,postPause:l.pause??.28,confidence:.84};if(sc==='descent / sealed spaces')Object.assign(d,{label:'cautious / tightening',emotionPreset:'tense',speedFactor:.97,tone:'crisp'});if(sc==='treasure / temptation'&&sp==='Kurash')Object.assign(d,{label:'tempted / rationalizing',emotionPreset:'tense',speedFactor:1.03,pitchDelta:.15,tone:'bright'});if(sc==='death / shock')Object.assign(d,{label:sp==='Narrator'?'shock / controlled':'shock / grief',emotionPreset:sp==='Narrator'?'tense':'grief',speedFactor:sp==='Narrator'?.92:.88,tone:'dark',postPause:Math.max(d.postPause,.5)});if(sc==='throne / journal')Object.assign(d,{label:'dread / contained',emotionPreset:'solemn',speedFactor:.9,pitchDelta:-.25,tone:'dark',postPause:Math.max(d.postPause,.42)});if(sp==='Dead King')Object.assign(d,{label:'ancient / dry / unnatural',emotionPreset:'ominous',speedFactor:.82,pitchDelta:-.7,tone:'dark',intensity:.9,postPause:Math.max(d.postPause,.85),confidence:.98});if(sp==='Bel-iddin')Object.assign(d,/second door|whatever you do/.test(t)?{label:'urgent / strained / intimate',emotionPreset:'urgent',speedFactor:.97,tone:'crisp'}:{label:'intimate / grave instruction',emotionPreset:'intimate',speedFactor:.92,tone:'warm'});if(sp==='Zik'&&/that.?s new/.test(t))Object.assign(d,{label:'shocked / suppressing reaction',emotionPreset:'deadpan',speedFactor:.91,pitchDelta:-.2,postPause:Math.max(d.postPause,.9)});if(/!/.test(l.text||'')&&d.emotionPreset==='neutral')Object.assign(d,{label:'heightened / immediate',emotionPreset:'urgent',speedFactor:1.03,intensity:1.04});return d}
function autoDirect(draw=true){const ls=chapter().lines||[];ls.forEach((l,i)=>{if(!l.directionLocked)l.autoDirection=direct(l,i,ls)});save();if(draw)render()}
function dFor(l){return l.directionLocked&&l.manualDirection?l.manualDirection:(l.autoDirection||direct(l,chapter().lines.indexOf(l),chapter().lines))}
function patchRender(){if(origRenderLine)return;origRenderLine=renderLine;renderLine=async l=>{const c=clone(charByName(l.speaker)),d=dFor(l);if(d){c.emotion=d.emotionPreset||c.emotion;c.speed=clamp((c.speed||1)*(d.speedFactor||1),.5,1.6);c.pitch=clamp((c.pitch||0)+(d.pitchDelta||0),-6,6);if(d.tone&&d.tone!=='neutral')c.tone=d.tone;c.intensity=clamp((c.intensity||1)*(d.intensity||1),.5,1.35)}return synthesizeProfile(l.text,c)}}
function patchVoice(){if(origSaveVoice)return;origSaveVoice=saveVoiceBase;saveVoiceBase=function(c,r=false){origSaveVoice(c,r);rememberChar(c)}}
