function applyDictionary(text){let out=String(text);for(const d of state.dictionary){const a=String(d.from||'').trim(),b=String(d.to||'').trim();if(!a||!b)continue;const re=new RegExp(`\b${a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\b`,'gi');out=out.replace(re,b)}return out;}
async function kokoroBlob(text,voice,speed=1){const t=await loadKokoro();const audio=await t.generate(applyDictionary(text),{voice,speed});let blob;if(typeof audio.toBlob==='function')blob=await audio.toBlob();else{const arr=audio.audio||audio.data;blob=encodeWav(arr,audio.sampling_rate||24000)}try{audio.audio=null;audio.data=null}catch{}return blob;}

async function loadCloneEngine(){if(cloneTTS)return cloneTTS;if(cloneLoading)return cloneLoading;cloneLoading=(async()=>{if(/iPhone|iPad|iPod/i.test(navigator.userAgent))throw new Error('Voice cloning is disabled on iPhone/iPad in this build because the clone model is too large for reliable mobile Safari use. Preset/designed/blended Kokoro voices still work.');if(!navigator.gpu&&!confirm('No WebGPU detected. Voice cloning may be extremely slow or run out of memory using WASM. Try anyway?'))throw new Error('Clone engine canceled because WebGPU is unavailable.');setStatus('Loading voice-clone engine…');let mod;try{mod=await import('https://esm.sh/voxshot?bundle&deps=@huggingface/transformers');}catch{mod=await import('https://esm.sh/voxshot?deps=@huggingface/transformers');}const engine=new mod.ChatterboxEngine({requiresGpu:false});cloneTTS=await mod.VoxShot.create({engine,device:navigator.gpu?'webgpu':'wasm',minChunkLength:20});setStatus(`Clone engine ready · ${cloneTTS.device||'auto'}`);return cloneTTS})();try{return await cloneLoading}finally{cloneLoading=null}}
async function cloneFromFile(c,file){if(!file)throw new Error('Choose a clean 5–15 second voice sample first.');const t=await loadCloneEngine();setStatus(`Cloning ${c.name}…`);await t.cloneVoice(file);const id=c.cloneId||`ashen-${slug(c.name)}-${Date.now()}`;await t.saveVoice(id);c.cloneId=id;c.cloneReady=true;c.cloneFileName=file.name;c.mode='clone';save();setStatus(`${c.name} clone saved`);}
async function clonedBlob(text,c){const t=await loadCloneEngine();if(!c.cloneReady||!c.cloneId)throw new Error(`${c.name} has no saved cloned voice.`);await t.useVoice(c.cloneId);const a=await t.speak(applyDictionary(text),{speed:c.speed,expressiveness:c.expressiveness});let blob;if(typeof a.toBlob==='function')blob=a.toBlob();else if(typeof a.toWav==='function')blob=new Blob([a.toWav()],{type:'audio/wav'});else blob=encodeWav(a.samples,a.sampleRate||24000);return blob;}

/*
  CLEAN AUDIO POLICY v0.7.1
  Kokoro already returns a finished speech waveform. The previous default path
  decoded that WAV, changed playbackRate for pitch, stacked EQ filters, applied
  gain/normalization, then encoded it again. On mobile Safari that produced the
  underwater/static character the user heard. Clean Kokoro output is now the
  default. The old DSP remains available only if a future build explicitly sets
  state.settings.studioProcessing === true.
*/
function studioProcessingEnabled(){return state?.settings?.studioProcessing===true&&!/iPhone|iPad|iPod/i.test(navigator.userAgent);}
async function synthesizeProfile(text,c){const em=EMOTIONS[c.emotion]||EMOTIONS.neutral;const speed=clamp((c.speed||1)*(em.speed||1),.5,1.6);const pitch=clamp((c.pitch||0)+(em.pitch||0),-6,6);const tone=c.tone==='neutral'?em.tone:c.tone;const intensity=clamp((c.intensity||1)*(em.intensity||1),.5,1.35);let blob;if(c.mode==='clone'){blob=await clonedBlob(text,{...c,speed,expressiveness:c.expressiveness??em.expr});}else if(c.mode==='blend'){const a=await kokoroBlob(text,c.blendA,speed);await sleep(30);const b=await kokoroBlob(text,c.blendB,speed);blob=await mixWavs(a,b,c.blendWeight);}else{blob=await kokoroBlob(text,c.voice,speed);}if(!studioProcessingEnabled())return blob;return processWav(blob,{pitch,tone,intensity});}
async function renderLine(l){const base=clone(charByName(l.speaker));if(l.emotion)base.emotion=l.emotion;const blob=await synthesizeProfile(l.text,base);return blob;}

async function processWav(blob,{pitch=0,tone='neutral',intensity=1}={}){if(Math.abs(pitch)<.001&&tone==='neutral'&&Math.abs(intensity-1)<.001)return blob;const AC=window.AudioContext||window.webkitAudioContext;const ac=new AC();let buf;try{buf=await ac.decodeAudioData((await blob.arrayBuffer()).slice(0));}finally{await ac.close().catch(()=>{})}const factor=Math.pow(2,pitch/12),frames=Math.max(1,Math.ceil(buf.length/factor));const OC=window.OfflineAudioContext||window.webkitOfflineAudioContext;const ctx=new OC(1,frames,buf.sampleRate),src=ctx.createBufferSource();src.buffer=buf;src.playbackRate.value=factor;let node=src;for(const f of toneFilters(tone)){const q=ctx.createBiquadFilter();q.type=f.type;q.frequency.value=f.frequency;if(f.gain!=null)q.gain.value=f.gain;if(f.Q!=null)q.Q.value=f.Q;node.connect(q);node=q}const gain=ctx.createGain();gain.gain.value=intensity;node.connect(gain);gain.connect(ctx.destination);src.start();const out=await ctx.startRendering();let pcm=new Float32Array(out.getChannelData(0));if(state.settings.normalize)pcm=normalizePcm(pcm,.94);return encodeWav(pcm,out.sampleRate);}
function toneFilters(t){return({warm:[{type:'lowshelf',frequency:250,gain:2},{type:'highshelf',frequency:4500,gain:-1.5}],dark:[{type:'highshelf',frequency:3200,gain:-3},{type:'lowshelf',frequency:220,gain:1}],bright:[{type:'highshelf',frequency:3200,gain:2.5}],crisp:[{type:'peaking',frequency:2700,gain:2,Q:.9}],soft:[{type:'lowpass',frequency:6500,Q:.5}],hollow:[{type:'peaking',frequency:850,gain:-3,Q:1.1},{type:'peaking',frequency:2300,gain:1.5,Q:1}],radio:[{type:'highpass',frequency:250,Q:.7},{type:'lowpass',frequency:3600,Q:.7}]}[t]||[]);}
function normalizePcm(pcm,target=.94){let peak=0;for(const x of pcm)peak=Math.max(peak,Math.abs(x));if(!peak||peak<=target)return pcm;const g=target/peak;const out=new Float32Array(pcm.length);for(let i=0;i<pcm.length;i++)out[i]=pcm[i]*g;return out;}
async function decode(blob){const AC=window.AudioContext||window.webkitAudioContext;const ac=new AC();try{return await ac.decodeAudioData((await blob.arrayBuffer()).slice(0))}finally{await ac.close().catch(()=>{})}}
async function mixWavs(a,b,w=.5){const [A,B]=await Promise.all([decode(a),decode(b)]),rate=A.sampleRate;const len=Math.max(A.length,Math.round(B.length*rate/B.sampleRate)),out=new Float32Array(len);const aa=A.getChannelData(0),bb=B.getChannelData(0);for(let i=0;i<len;i++){const av=aa[Math.min(aa.length-1,i)]||0;const bi=Math.floor(i*B.sampleRate/rate),bv=bb[Math.min(bb.length-1,bi)]||0;out[i]=av*w+bv*(1-w)}return encodeWav(normalizePcm(out,.92),rate);}
function encodeWav(samples,sampleRate=24000){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b),ascii=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};ascii(0,'RIFF');v.setUint32(4,36+samples.length*2,true);ascii(8,'WAVE');ascii(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);ascii(36,'data');v.setUint32(40,samples.length*2,true);let o=44;for(const raw of samples){const s=Math.max(-1,Math.min(1,raw));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return new Blob([b],{type:'audio/wav'});}
async function merge(blobs,pauses){const decoded=[];for(const b of blobs)decoded.push(await decode(b));const rate=decoded[0].sampleRate,total=decoded.reduce((n,x,i)=>n+Math.round(x.length*rate/x.sampleRate)+Math.round((pauses[i]||0)*rate),0),pcm=new Float32Array(total);let cur=0;for(let j=0;j<decoded.length;j++){const x=decoded[j],src=x.getChannelData(0),scaled=x.sampleRate===rate?src:resample(src,x.sampleRate,rate);pcm.set(scaled,cur);cur+=scaled.length+Math.round((pauses[j]||0)*rate)}return encodeWav(state.settings.normalize?normalizePcm(pcm,.94):pcm,rate);}
function resample(src,inRate,outRate){if(inRate===outRate)return src;const len=Math.round(src.length*outRate/inRate),out=new Float32Array(len);for(let i=0;i<len;i++){const x=i*inRate/outRate,lo=Math.floor(x),hi=Math.min(src.length-1,lo+1),t=x-lo;out[i]=src[lo]*(1-t)+src[hi]*t}return out;}
