function applyDictionary(text){let out=String(text);for(const d of state.dictionary){const a=String(d.from||'').trim(),b=String(d.to||'').trim();if(!a||!b)continue;const re=new RegExp(`\\b${a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'gi');out=out.replace(re,b)}return out;}
async function kokoroBlob(text,voice,speed=1){const t=await loadKokoro();const audio=await t.generate(applyDictionary(text),{voice,speed});let blob;if(typeof audio.toBlob==='function')blob=await audio.toBlob();else{const arr=audio.audio||audio.data;blob=encodeWav(arr,audio.sampling_rate||24000)}try{audio.audio=null;audio.data=null}catch{}return blob;}

async function loadCloneEngine(){if(cloneTTS)return cloneTTS;if(cloneLoading)return cloneLoading;cloneLoading=(async()=>{if(/iPhone|iPad|iPod/i.test(navigator.userAgent))throw new Error('Voice cloning is disabled on iPhone/iPad in this build because the clone model is too large for reliable mobile Safari use. Preset/designed/blended Kokoro voices still work.');if(!navigator.gpu&&!confirm('No WebGPU detected. Voice cloning may be extremely slow or run out of memory using WASM. Try anyway?'))throw new Error('Clone engine canceled because WebGPU is unavailable.');setStatus('Loading voice-clone engine…');let mod;try{mod=await import('https://esm.sh/voxshot?bundle&deps=@huggingface/transformers');}catch{mod=await import('https://esm.sh/voxshot?deps=@huggingface/transformers');}const engine=new mod.ChatterboxEngine({requiresGpu:false});cloneTTS=await mod.VoxShot.create({engine,device:navigator.gpu?'webgpu':'wasm',minChunkLength:20});setStatus(`Clone engine ready · ${cloneTTS.device||'auto'}`);return cloneTTS})();try{return await cloneLoading}finally{cloneLoading=null}}
async function cloneFromFile(c,file){if(!file)throw new Error('Choose a clean 5–15 second voice sample first.');const t=await loadCloneEngine();setStatus(`Cloning ${c.name}…`);await t.cloneVoice(file);const id=c.cloneId||`ashen-${slug(c.name)}-${Date.now()}`;await t.saveVoice(id);c.cloneId=id;c.cloneReady=true;c.cloneFileName=file.name;c.mode='clone';save();setStatus(`${c.name} clone saved`);}
async function clonedBlob(text,c){const t=await loadCloneEngine();if(!c.cloneReady||!c.cloneId)throw new Error(`${c.name} has no saved cloned voice.`);await t.useVoice(c.cloneId);const a=await t.speak(applyDictionary(text),{speed:c.speed,expressiveness:c.expressiveness});let blob;if(typeof a.toBlob==='function')blob=a.toBlob();else if(typeof a.toWav==='function')blob=new Blob([a.toWav()],{type:'audio/wav'});else blob=encodeWav(a.samples,a.sampleRate||24000);return blob;}

async function synthesizeProfile(text,c){const em=EMOTIONS[c.emotion]||EMOTIONS.neutral;const speed=clamp((c.speed||1)*(em.speed||1),.5,1.6);const pitch=clamp((c.pitch||0)+(em.pitch||0),-6,6);const tone=c.tone==='neutral'?em.tone:c.tone;const intensity=clamp((c.intensity||1)*(em.intensity||1),.5,1.35);let blob;if(c.mode==='clone'){blob=await clonedBlob(text,{...c,speed,expressiveness:c.expressiveness??em.expr});}else if(c.mode==='blend'){const a=await kokoroBlob(text,c.blendA,speed);await sleep(30);const b=await kokoroBlob(text,c.blendB,speed);blob=await mixWavs(a,b,c.blendWeight); }else{blob=await kokoroBlob(text,c.voice,speed);}return processWav(blob,{pitch,tone,intensity});}
async function renderLine(l){const base=clone(charByName(l.speaker));if(l.emotion)base.emotion=l.emotion;const blob=await synthesizeProfile(l.text,base);return blob;}

async function processWav(blob,{pitch=0,tone='neutral',intensity=1}={}){if(Math.abs(pitch)<.001&&tone==='neutral'&&Math.abs(intensity-1)<.001)return blob;const AC=window.AudioContext||window.webkitAudioContext;const ac=new AC();let buf;try{buf=await ac.decodeAudioData((await blob.arrayBuffer()).slice(0));}finally{await ac.close().catch(()=>{})}const factor=Math.pow(2,pitch/12),frames=Math.max(1,Math.ceil(buf.length/factor));const OC=window.OfflineAudioContext||window.webkitOfflineAudioContext;const ctx=new OC(1,frames,buf.sampleRate),src=ctx.createBufferSource();src.buffer=buf;src.playbackRate.value=factor;let node=src;for(const f of toneFilters(tone)){const q=ctx.createBiquadFilter();q.type=f.type;q.frequency.value=f.frequency;if(f.gain!=null)q.gain.value=f.gain;if(f.Q!=null)q.Q.value=f.Q;node.connect(q);node=q}const gain=ctx.createGain();gain.gain.value=intensity;node.connect(gain);gain.connect(ctx.destination);src.start();const out=await ctx.startRendering();let pcm=new Float32Array(out.getChannelData(0));if(state.settings.normalize)pcm=normalizePcm(pcm,.94);return encodeWav(pcm,out.sampleRate);}
function toneFilters(t){return({warm:[{type:'lowshelf',frequency:250,gain:2},{type:'highshelf',frequency:4500,gain:-1.5}],dark:[{type:'highshelf',frequency:3200,gain:-3},{type:'lowshelf',frequency:220,gain:1}],bright:[{type:'highshelf',frequency:3200,gain:2.5}],crisp:[{type:'peaking',frequency:2700,gain:2,Q:.9}],soft:[{type:'lowpass',frequency:6500,Q:.5}],hollow:[{type:'peaking',frequency:850,gain:-3,Q:1.1},{type:'peaking',frequency:2300,gain:1.5,Q:1}],radio:[{type:'highpass',frequency:250,Q:.7},{type:'lowpass',frequency:3600,Q:.7}]}[t]||[]);}
function normalizePcm(pcm,target=.94){let peak=0;for(const x of pcm)peak=Math.max(peak,Math.abs(x));if(!peak||peak<=target)return pcm;const g=target/peak;const out=new Float32Array(pcm.length);for(let i=0;i<pcm.length;i++)out[i]=pcm[i]*g;return out;}
async function decode(blob){const AC=window.AudioContext||window.webkitAudioContext;const ac=new AC();try{return await ac.decodeAudioData((await blob.arrayBuffer()).slice(0))}finally{await ac.close().catch(()=>{})}}
async function mixWavs(a,b,w=.5){const [A,B]=await Promise.all([decode(a),decode(b)]),rate=A.sampleRate;const len=Math.max(A.length,Math.round(B.length*rate/B.sampleRate)),out=new Float32Array(len);const aa=A.getChannelData(0),bb=B.getChannelData(0);for(let i=0;i<len;i++){const av=aa[Math.min(aa.length-1,i)]||0;const bi=Math.floor(i*B.sampleRate/rate),bv=bb[Math.min(bb.length-1,bi)]||0;out[i]=av*w+bv*(1-w)}return encodeWav(normalizePcm(out,.92),rate);}
function encodeWav(samples,sampleRate=24000){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b),ascii=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};ascii(0,'RIFF');v.setUint32(4,36+samples.length*2,true);ascii(8,'WAVE');ascii(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);ascii(36,'data');v.setUint32(40,samples.length*2,true);let o=44;for(const raw of samples){const s=Math.max(-1,Math.min(1,raw));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return new Blob([b],{type:'audio/wav'});}
async function merge(blobs,pauses){const decoded=[];for(const b of blobs)decoded.push(await decode(b));const rate=decoded[0].sampleRate,total=decoded.reduce((n,x,i)=>n+Math.round(x.length*rate/x.sampleRate)+Math.round((pauses[i]||0)*rate),0),pcm=new Float32Array(total);let cur=0;for(let j=0;j<decoded.length;j++){const x=decoded[j],src=x.getChannelData(0),scaled=x.sampleRate===rate?src:resample(src,x.sampleRate,rate);pcm.set(scaled,cur);cur+=scaled.length+Math.round((pauses[j]||0)*rate)}return encodeWav(state.settings.normalize?normalizePcm(pcm,.94):pcm,rate);}
function resample(src,inRate,outRate){if(inRate===outRate)return src;const len=Math.round(src.length*outRate/inRate),out=new Float32Array(len);for(let i=0;i<len;i++){const x=i*inRate/outRate,lo=Math.floor(x),hi=Math.min(src.length-1,lo+1),t=x-lo;out[i]=src[lo]*(1-t)+src[hi]*t}return out;}

async function generateOne(id,{quiet=false}={}){const l=chapter().lines.find(x=>x.id===id);if(!l)return false;setStatus(`Rendering ${l.speaker}…`);try{const blob=await renderLine(l);await dbPut(lineKey(l),blob);l.generated=true;chapter().masterReady=false;await dbDel(masterKey()).catch(()=>{});save();if(state.settings.memorySaver)await sleep(40);if(!quiet)render();return true}catch(e){console.error(e);l.generated=false;save();if(!quiet)alert(`Render failed: ${e.message}`);return false}}
async function generateMissing(){queueAbort=false;const todo=chapter().lines.filter(l=>!l.generated&&l.text.trim());let n=0;for(const l of todo){if(queueAbort)break;const ok=await generateOne(l.id,{quiet:true});if(!ok)break;n++;setProgress(n,todo.length,'WAVs rendered');if(state.settings.memorySaver&&n%8===0)await sleep(120)}setStatus(queueAbort?'Stopped':'Generation pass finished');render();}
async function produceChapter(){queueAbort=false;if(Object.values(intake).some(Boolean))await mapFiles(true);if(!chapter().lines.length)throw alert('No production segments yet. Load your production/manuscript files first.');const todo=chapter().lines.filter(l=>!l.generated);let n=0;for(const l of todo){if(queueAbort)break;const ok=await generateOne(l.id,{quiet:true});if(!ok)break;n++;setProgress(n,todo.length,'Producing chapter');}if(!queueAbort){await assemble(true);setStatus('Chapter complete')}render();}
async function assemble(silent=false){const blobs=[],pauses=[];for(const l of chapter().lines){const b=await dbGet(lineKey(l));if(!b)continue;blobs.push(b);const c=charByName(l.speaker),em=EMOTIONS[l.emotion||c.emotion]||EMOTIONS.neutral;pauses.push(l.pause??c.pause??em.pause)}if(!blobs.length){if(!silent)alert('No WAVs generated yet.');return}setStatus('Assembling master WAV…');const out=await merge(blobs,pauses);await dbPut(masterKey(),out);chapter().masterReady=blobs.length===chapter().lines.length;save();if(!silent)render();return out;}
async function previewCharacter(id){if(voicePreviewBusy)return;unlockPreviewAudio();const c=state.characters.find(x=>x.id===id);if(!c)return;const sample=previewText(c.name).slice(0,state.settings.memorySaver?72:140);setVoiceBusy(true,`Preparing ${c.name} preview…`);try{const b=await synthesizeProfile(sample,c);await playBlob(b,`${c.name} voice preview`);setEngineProgress(`${c.name} preview ready`,false)}catch(e){alert(`Preview failed: ${e.message}`);setEngineProgress('Preview failed',false)}finally{setVoiceBusy(false)}}
async function previewLine(id){if(voicePreviewBusy)return;unlockPreviewAudio();const l=chapter().lines.find(x=>x.id===id);if(!l)return;const short={...l,text:l.text.slice(0,state.settings.memorySaver?80:160)};setVoiceBusy(true,`Preparing line preview · ${l.speaker}…`);try{const b=await renderLine(short);await playBlob(b,`${l.speaker} · line preview`);setEngineProgress('Line preview ready',false)}catch(e){alert(`Preview failed: ${e.message}`);setEngineProgress('Preview failed',false)}finally{setVoiceBusy(false)}}
let previewAudioContext=null;
let previewBufferSource=null;
let previewUnlockPromise=null;

function unlockPreviewAudio(){
  const AC=window.AudioContext||window.webkitAudioContext;
  if(!AC)return Promise.resolve(false);
  try{
    if(!previewAudioContext)previewAudioContext=new AC();
    previewUnlockPromise=previewAudioContext.state==='suspended'
      ? previewAudioContext.resume().catch(()=>false)
      : Promise.resolve(true);
    const b=previewAudioContext.createBuffer(1,1,previewAudioContext.sampleRate||24000);
    const s=previewAudioContext.createBufferSource();
    s.buffer=b;s.connect(previewAudioContext.destination);s.start(0);
    return previewUnlockPromise;
  }catch(e){console.warn('Audio unlock failed',e);return Promise.resolve(false);}
}
function showPreviewDock(blob,label='Voice preview'){const dock=byId('previewDock'),audio=byId('previewDockAudio'),title=byId('previewDockTitle'),st=byId('previewDockStatus');if(!dock||!audio)return null;const u=URL.createObjectURL(blob);objectUrls.push(u);title.textContent=label;st.textContent='Preview ready. If Safari blocks automatic sound, tap Play below.';audio.src=u;audio.load();dock.classList.add('show');return {audio,url:u,status:st};}
async function playBlob(blob,label='Voice preview'){const dock=showPreviewDock(blob,label);try{await(previewUnlockPromise||Promise.resolve());const AC=window.AudioContext||window.webkitAudioContext;if(!previewAudioContext&&AC)previewAudioContext=new AC();if(previewAudioContext){if(previewAudioContext.state==='suspended')await previewAudioContext.resume();const arr=await blob.arrayBuffer();const buf=await previewAudioContext.decodeAudioData(arr.slice(0));try{previewBufferSource?.stop()}catch{}const src=previewAudioContext.createBufferSource();src.buffer=buf;src.connect(previewAudioContext.destination);previewBufferSource=src;src.onended=()=>{if(dock?.status)dock.status.textContent='Preview finished. Tap Play to hear it again.'};src.start(0);if(dock?.status)dock.status.textContent='Playing preview…';return true}}catch(e){console.warn('Web Audio autoplay path failed',e)}if(dock?.audio){try{await dock.audio.play();dock.status.textContent='Playing preview…';return true}catch(e){dock.status.textContent='Safari blocked automatic playback. Tap Play below.';console.warn('HTML audio autoplay blocked',e)}}return false;}
async function clearChapterAudio(){if(!confirm('Clear all generated audio for this chapter?'))return;for(const l of chapter().lines){await dbDel(lineKey(l)).catch(()=>{});l.generated=false}await dbDel(masterKey()).catch(()=>{});chapter().masterReady=false;save();render();}
async function restoreAudio(){for(const l of chapter().lines.filter(x=>x.generated)){const b=await dbGet(lineKey(l)).catch(()=>null);if(!b)continue;const h=byId(`audio-${l.id}`);if(!h)continue;const u=URL.createObjectURL(b);objectUrls.push(u);h.innerHTML=`<audio controls preload="metadata" src="${u}"></audio><button class="btn tiny saveLine">Share WAV</button>`;h.querySelector('.saveLine').onclick=()=>shareBlob(b,`${slug(l.speaker)}-${l.id.slice(0,5)}.wav`)}const master=await dbGet(masterKey()).catch(()=>null);if(master&&byId('master')){const u=URL.createObjectURL(master);objectUrls.push(u);byId('master').innerHTML=`<div class="master"><strong>Chapter Master</strong><div class="audioRow"><audio controls src="${u}"></audio></div><div class="toolbar"><button id="shareMaster" class="btn good">Save / Share Final WAV</button></div></div>`;byId('shareMaster').onclick=()=>shareBlob(master,`${slug(state.title)}-${slug(chapter().title)}.wav`)}}
function revokeUrls(){for(const u of objectUrls)URL.revokeObjectURL(u);objectUrls=[];}
async function shareBlob(blob,name){const f=new File([blob],name,{type:blob.type||'audio/wav'});if(navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],title:name});return}catch(e){if(e.name==='AbortError')return}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),20000)}
