
// ASHEN VOICE STUDIO v0.5 — single-file phone-first build
const VERSION='0.7.0';
const KOKORO_MODEL='onnx-community/Kokoro-82M-v1.0-ONNX';
const STORAGE_KEY='ashen-voice-v070-state';
const DB_NAME='ashen-voice-v070'; const DB_STORE='clips';
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const clone=o=>globalThis.structuredClone?structuredClone(o):JSON.parse(JSON.stringify(o));
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||a));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const byId=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const slug=s=>String(s||'audio').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'audio';

const VOICES=[
['af_heart','Heart · American female'],['af_bella','Bella · American female'],['af_nicole','Nicole · American female'],['af_kore','Kore · American female'],['af_sarah','Sarah · American female'],['af_aoede','Aoede · American female'],['af_nova','Nova · American female'],['af_alloy','Alloy · American female'],['af_jessica','Jessica · American female'],['af_river','River · American female'],['af_sky','Sky · American female'],
['am_fenrir','Fenrir · American male'],['am_michael','Michael · American male'],['am_puck','Puck · American male'],['am_onyx','Onyx · American male'],['am_eric','Eric · American male'],['am_echo','Echo · American male'],['am_liam','Liam · American male'],['am_adam','Adam · American male'],
['bf_emma','Emma · British female'],['bf_isabella','Isabella · British female'],['bf_alice','Alice · British female'],['bf_lily','Lily · British female'],['bm_george','George · British male'],['bm_lewis','Lewis · British male'],['bm_daniel','Daniel · British male'],['bm_fable','Fable · British male']
];
const TONES=['neutral','warm','dark','bright','crisp','soft','hollow','radio'];
const EMOTIONS={
neutral:{speed:.96,pitch:0,tone:'neutral',pause:.34,intensity:1,expr:.5},solemn:{speed:.88,pitch:-.8,tone:'dark',pause:.48,intensity:.94,expr:.38},tense:{speed:.97,pitch:.5,tone:'crisp',pause:.35,intensity:1.03,expr:.72},urgent:{speed:1.08,pitch:.7,tone:'bright',pause:.22,intensity:1.06,expr:.8},fearful:{speed:1.02,pitch:1.25,tone:'bright',pause:.38,intensity:.95,expr:.78},grief:{speed:.85,pitch:-1.1,tone:'warm',pause:.58,intensity:.86,expr:.45},angry:{speed:1.01,pitch:-.4,tone:'crisp',pause:.25,intensity:1.10,expr:.9},intimate:{speed:.90,pitch:-.3,tone:'warm',pause:.44,intensity:.84,expr:.35},deadpan:{speed:.93,pitch:-.5,tone:'neutral',pause:.38,intensity:.91,expr:.2},ominous:{speed:.84,pitch:-1.6,tone:'dark',pause:.62,intensity:.92,expr:.5},whispered:{speed:.89,pitch:.15,tone:'soft',pause:.46,intensity:.72,expr:.28}
};
const DESC_LIBRARY={
'deep':{voice:'am_onyx',pitch:-2,tone:'dark',speed:.9},'gravel':{voice:'bm_george',pitch:-1.4,tone:'crisp',speed:.9},'rough':{voice:'bm_george',pitch:-1.1,tone:'crisp',speed:.94},'old':{voice:'bm_lewis',pitch:-.8,tone:'warm',speed:.88},'young':{voice:'am_puck',pitch:.9,tone:'bright',speed:1.02},'warm':{voice:'am_michael',pitch:-.3,tone:'warm',speed:.94},'cold':{voice:'am_onyx',pitch:-.7,tone:'crisp',speed:.92},'menacing':{voice:'am_fenrir',pitch:-1.3,tone:'dark',speed:.88},'scholarly':{voice:'bm_daniel',pitch:0,tone:'warm',speed:.92},'calm':{voice:'am_michael',pitch:-.2,tone:'soft',speed:.9},'female':{voice:'af_heart',pitch:0,tone:'neutral',speed:.96},'older woman':{voice:'bf_emma',pitch:-.7,tone:'warm',speed:.88},'young woman':{voice:'af_bella',pitch:.5,tone:'bright',speed:1},'british':{voice:'bm_daniel',pitch:0,tone:'neutral',speed:.95},'american':{voice:'am_michael',pitch:0,tone:'neutral',speed:.96},'soft':{voice:'af_heart',pitch:0,tone:'soft',speed:.9},'commanding':{voice:'am_fenrir',pitch:-.8,tone:'crisp',speed:.96}
};

let kokoro=null,kokoroLoading=null,cloneTTS=null,cloneLoading=null,queueAbort=false,objectUrls=[],selectedCharacterId=null;
const intake={production:null,manuscript:null,pronunciation:null,guide:null};
let state=null; selectedCharacterId=null;

function freshState(){const chapter={id:uid(),title:'Chapter One',lines:[],masterReady:false};return{schema:5,title:'The First City',author:'C. R. Ashen',activeChapterId:chapter.id,chapters:[chapter],characters:[makeChar({name:'Narrator',voice:'am_michael',speed:.94,pause:.42})],dictionary:[],settings:{dtype:'q4',device:'auto',memorySaver:true,normalize:true,fadeMs:10},sources:{productionText:'',manuscriptText:'',pronunciationText:'',guideText:'',names:{}},guideNotes:'',updatedAt:Date.now()};}
function makeChar(c={}){return{id:c.id||uid(),name:c.name||'Character',mode:c.mode||'preset',voice:c.voice||'am_fenrir',speed:clamp(c.speed??.96,.5,1.6),pause:Math.max(0,Number(c.pause??.34)),pitch:clamp(c.pitch??0,-6,6),tone:TONES.includes(c.tone)?c.tone:'neutral',emotion:EMOTIONS[c.emotion]?c.emotion:'neutral',intensity:clamp(c.intensity??1,.5,1.35),expressiveness:clamp(c.expressiveness??.5,0,1.5),blendA:c.blendA||'am_fenrir',blendB:c.blendB||'am_michael',blendWeight:clamp(c.blendWeight??.5,0,1),description:c.description||'',cloneId:c.cloneId||'',cloneReady:!!c.cloneReady,cloneFileName:c.cloneFileName||''};}
function migrate(s){if(!s)return freshState();s.schema=5;s.settings={dtype:'q4',device:'auto',memorySaver:true,normalize:true,fadeMs:10,...s.settings};s.characters=(s.characters||[]).map(makeChar);if(!s.characters.length)s.characters=freshState().characters;s.dictionary=Array.isArray(s.dictionary)?s.dictionary:[];s.chapters=(s.chapters||[]).map(ch=>({...ch,id:ch.id||uid(),lines:(ch.lines||[]).map(l=>({...l,id:l.id||uid(),speaker:l.speaker||'Narrator',generated:false}))}));if(!s.chapters.length){const f=freshState();s.chapters=f.chapters;s.activeChapterId=f.activeChapterId;}if(!s.activeChapterId||!s.chapters.some(c=>c.id===s.activeChapterId))s.activeChapterId=s.chapters[0].id;s.sources=s.sources||freshState().sources;return s;}
function loadState(){try{return migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'));}catch{return freshState();}}
function save(){state.updatedAt=Date.now();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateStats();}
function chapter(){return state.chapters.find(c=>c.id===state.activeChapterId)||state.chapters[0];}
function charByName(name){return state.characters.find(c=>c.name.toLowerCase()===String(name).toLowerCase())||state.characters[0];}
function ensureChar(name){let c=state.characters.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!c){c=makeChar({name});state.characters.push(c);}return c;}
function lineKey(l){return `${state.title}:${chapter().id}:${l.id}`;}function masterKey(){return `${state.title}:${chapter().id}:MASTER`;}

function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function dbPut(k,v){const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}
async function dbGet(k){const db=await openDb();const out=await new Promise((res,rej)=>{const r=db.transaction(DB_STORE,'readonly').objectStore(DB_STORE).get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});db.close();return out;}
async function dbDel(k){const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}

function fileSlot(kind,title,desc,accept){const f=intake[kind];return `<label class="fileCard"><div class="fileBadge">${kind.slice(0,4).toUpperCase()}</div><div class="fileMeta"><strong>${title}</strong><p class="mini">${desc}</p><div class="fileName">${f?esc(f.name):'Tap to choose file'}</div></div><input class="hiddenInput intakeFile" data-kind="${kind}" type="file" accept="${accept}"></label>`;}
function render(){revokeUrls();const ch=chapter(),done=ch.lines.filter(l=>l.generated).length;byId('app').innerHTML=`<main class="shell"><header class="top"><div class="brand"><div class="logo">AV</div><div><h1>Ashen Voice Studio <span class="version">v${VERSION}</span></h1><p>repo-backed audiobook production + voice lab</p></div></div><div id="status" class="status">Ready</div></header>
<section class="panel"><div class="sectionHead"><div><h2>Project Sources</h2><div class="mini">Book data loads automatically from this repository. Manual file slots remain as an emergency fallback.</div></div><span class="chip">GitHub-backed</span></div><div class="fileGrid">${fileSlot('production','1 · Production','Speaker assignments / production JSON','.json,.txt,.md')}${fileSlot('manuscript','2 · Manuscript','Chapter source text','.txt,.md')}${fileSlot('pronunciation','3 · Pronunciations','Written → spoken replacements','.txt,.csv,.json,.md')}${fileSlot('guide','4 · Production Guide','Cast defaults and performance notes','.txt,.md')}</div><div class="toolbar workflow"><button id="mapFiles" class="btn">Map Files</button><button id="openVoices" class="btn primary">Choose / Build Voices</button><button id="produce" class="btn good">Produce Chapter WAV</button><button id="stop" class="btn bad">Stop</button></div><div class="progressWrap"><div class="progress"><div id="progressBar"></div></div><div id="progressText" class="progressText">Idle</div></div></section>
<div class="grid2"><section class="panel"><div class="sectionHead"><h2>Project</h2><span class="chip">local autosave</span></div><div class="field"><label>Book</label><input id="bookTitle" value="${esc(state.title)}"></div><div class="field"><label>Author</label><input id="authorName" value="${esc(state.author)}"></div><div class="field"><label>Chapter</label><input id="chapterTitle" value="${esc(ch.title)}"></div><div class="toolbar"><button id="backup" class="btn">Backup Project</button><label class="btn">Restore<input id="restore" class="hiddenInput" type="file" accept=".json"></label></div></section><section class="panel"><div class="sectionHead"><h2>Voice Engine</h2><span class="chip">Kokoro / local browser</span></div><div class="field"><label>Device</label><select id="device"><option value="auto">Auto</option><option value="webgpu">WebGPU</option><option value="wasm">WASM</option></select></div><div class="field"><label>Precision</label><select id="dtype"><option value="q4">q4</option><option value="q8">q8</option><option value="fp16">fp16</option><option value="fp32">fp32</option></select></div><div class="toolbar"><button id="loadK" class="btn primary">Load Voice Engine</button><button id="cancelK" class="btn bad" disabled>Cancel Engine</button><button id="toggleMemory" class="btn">Memory Saver: ${state.settings.memorySaver?'ON':'OFF'}</button></div><div class="engineBox"><div class="engineRow"><div id="engineProgress" class="engineProgress">Voice engine not loaded. First load can take a while; the interface will remain responsive.</div></div></div><div class="memoryBanner">Memory Saver is ${state.settings.memorySaver?'ON':'OFF'}: compact model precision, short previews, one render at a time.</div><pre id="runtimeErrorBox" class="mini" style="white-space:pre-wrap;color:#efada6;max-height:90px;overflow:auto"></pre><div id="stats" class="stats"></div></section></div>
<section class="panel"><div class="sectionHead"><div><h2>Cast Voice Studio</h2><div class="mini">Every speaker gets a persistent voice card. Edit any card before or after mapping the chapter.</div></div><button id="addCharacter" class="btn">+ Character</button></div><div class="castList">${state.characters.map(c=>`<div class="castCard"><div class="castHead"><strong>${esc(c.name)}</strong><span class="chip">${esc(c.mode)}</span></div><div class="recipe">${esc(profileSummary(c))}</div><div class="toolbar"><button class="btn tiny editVoice" data-id="${c.id}">Edit Character / Voice</button><button class="btn tiny quickPreview" data-id="${c.id}">▶ Preview</button></div></div>`).join('')}</div></section>
<section class="panel"><div class="sectionHead"><div><h2>Chapter Lines</h2><div class="mini">Speaker assignment, emotion, text and pause are editable per line.</div></div><span class="chip">${ch.lines.length} lines</span></div><div id="lines" class="lines">${ch.lines.map(lineHtml).join('')}</div></section>
<div id="voiceModal" class="modal hidden"></div>
<div id="previewDock" class="previewDock"><div class="previewDockHead"><strong id="previewDockTitle">Preview</strong><button id="previewDockClose" class="btn tiny">×</button></div><div class="mini" id="previewDockStatus">Preparing audio…</div><audio id="previewDockAudio" controls preload="auto"></audio></div>
<div class="bottomBar"><button class="btn" onclick="document.querySelector('.castList')?.scrollIntoView({behavior:'smooth'})">Cast</button><button class="btn" onclick="document.querySelector('#lines')?.scrollIntoView({behavior:'smooth'})">Lines</button><button class="btn primary" onclick="byId('produce')?.click()">Produce</button></div></main>`;wire();restoreMaster();updateStats();}
function profileSummary(c){const voice=VOICES.find(v=>v[0]===c.voice)?.[1]||c.voice;return `${voice} · ${c.emotion} · ${c.tone} · ${c.speed.toFixed(2)}x · pitch ${c.pitch>=0?'+':''}${c.pitch}`;}
function lineHtml(l){return `<div class="lineCard ${l.generated?'done':''}" id="line-${l.id}"><div class="lineTop"><select class="lineSpeaker" data-id="${l.id}">${state.characters.map(c=>`<option ${c.name===l.speaker?'selected':''}>${esc(c.name)}</option>`).join('')}</select><select class="lineEmotion" data-id="${l.id}">${Object.keys(EMOTIONS).map(x=>`<option ${x===l.emotion?'selected':''}>${x}</option>`).join('')}</select><input class="linePause" data-id="${l.id}" type="number" step=".05" min="0" max="3" placeholder="pause" value="${l.pause??''}"></div><textarea class="lineText" data-id="${l.id}">${esc(l.text)}</textarea><div class="toolbar"><button class="btn tiny previewOne" data-id="${l.id}">▶ Preview</button><button class="btn tiny genOne" data-id="${l.id}">${l.generated?'Regenerate':'Generate WAV'}</button><span class="chip">${esc(l.type||'line')}</span></div><div class="audioRow" id="audio-${l.id}"></div></div>`;}
function wire(){if(byId('previewDockClose'))byId('previewDockClose').onclick=()=>{const d=byId('previewDock');const a=byId('previewDockAudio');if(a){a.pause();a.removeAttribute('src');a.load()}if(d)d.classList.remove('show')};document.querySelectorAll('.intakeFile').forEach(x=>x.onchange=e=>{intake[e.target.dataset.kind]=e.target.files?.[0]||null;render()});byId('mapFiles').onclick=()=>mapFiles();byId('openVoices').onclick=()=>openVoiceLab(selectedCharacterId||state.characters[0]?.id);byId('produce').onclick=()=>produceChapter();byId('stop').onclick=()=>{queueAbort=true};byId('bookTitle').onchange=e=>{state.title=e.target.value;save()};byId('authorName').onchange=e=>{state.author=e.target.value;save()};byId('chapterTitle').onchange=e=>{chapter().title=e.target.value;save()};byId('device').value=state.settings.device;byId('dtype').value=state.settings.dtype;byId('device').onchange=e=>{state.settings.device=e.target.value;stopKokoroWorker('Engine setting changed');save()};byId('dtype').onchange=e=>{state.settings.dtype=e.target.value;stopKokoroWorker('Engine setting changed');save()};byId('loadK').onclick=async()=>{try{await loadKokoro()}catch(e){alert('Voice engine could not load on this device: '+(e?.message||e));setStatus('Voice engine failed · app still usable')}};byId('cancelK').onclick=()=>stopKokoroWorker('Voice engine canceled');byId('toggleMemory').onclick=()=>{state.settings.memorySaver=!state.settings.memorySaver;if(state.settings.memorySaver)state.settings.dtype='q4';stopKokoroWorker('Memory mode changed');save();render()};byId('backup').onclick=backup;byId('restore').onchange=restore;byId('addCharacter').onclick=addCharacter;document.querySelectorAll('.editVoice').forEach(b=>b.onclick=()=>openVoiceLab(b.dataset.id));document.querySelectorAll('.quickPreview').forEach(b=>b.onclick=()=>previewCharacter(b.dataset.id));document.querySelectorAll('.lineSpeaker').forEach(x=>x.onchange=e=>editLine(e.target.dataset.id,{speaker:e.target.value},true));document.querySelectorAll('.lineEmotion').forEach(x=>x.onchange=e=>editLine(e.target.dataset.id,{emotion:e.target.value},true));document.querySelectorAll('.linePause').forEach(x=>x.onchange=e=>editLine(e.target.dataset.id,{pause:e.target.value===''?null:Number(e.target.value)},true));document.querySelectorAll('.lineText').forEach(x=>x.onchange=e=>editLine(e.target.dataset.id,{text:e.target.value},true));document.querySelectorAll('.genOne').forEach(b=>b.onclick=()=>generateOne(b.dataset.id));document.querySelectorAll('.previewOne').forEach(b=>b.onclick=()=>previewLine(b.dataset.id));}

async function mapFiles(silent=false){setStatus('Reading production files…');try{if(intake.production){const t=await intake.production.text();state.sources.productionText=t;state.sources.names.production=intake.production.name;applyProduction(t)}if(intake.manuscript){const t=await intake.manuscript.text();state.sources.manuscriptText=t;state.sources.names.manuscript=intake.manuscript.name;if(!chapter().lines.length)applyManuscript(t)}if(intake.pronunciation){const t=await intake.pronunciation.text();state.sources.pronunciationText=t;state.sources.names.pronunciation=intake.pronunciation.name;applyPronunciations(t)}if(intake.guide){const t=await intake.guide.text();state.sources.guideText=t;state.sources.names.guide=intake.guide.name;state.guideNotes=t;applyGuide(t)}intake.production=intake.manuscript=intake.pronunciation=intake.guide=null;save();if(!silent)render();setStatus('Files mapped');}catch(e){alert(`Could not map files: ${e.message}`);setStatus('File mapping failed');}}
function applyProduction(text){try{const p=JSON.parse(text);if(Array.isArray(p.characters))p.characters.forEach(c=>{const ex=ensureChar(c.name);Object.assign(ex,makeChar({...ex,...c,id:ex.id}))});const lines=p.lines||p.segments||p.chapter?.lines||p.chapters?.[0]?.lines;if(Array.isArray(lines)){chapter().lines=lines.map(l=>({id:l.id||uid(),text:l.text||l.content||'',speaker:l.speaker||'Narrator',type:l.type||((l.speaker&&l.speaker!=='Narrator')?'dialogue':'narration'),confidence:l.confidence??1,emotion:l.emotion||'neutral',pause:l.pause??null,note:l.note||'',generated:false}));chapter().lines.forEach(l=>ensureChar(l.speaker));}if(p.title)chapter().title=p.title;if(p.dictionary)state.dictionary=p.dictionary.map(d=>({id:d.id||uid(),from:d.from||d.written||'',to:d.to||d.spoken||''}));}catch{chapter().lines=parseText(text);}}
function applyManuscript(text){chapter().lines=parseText(text);}
function applyPronunciations(text){let arr=[];try{const j=JSON.parse(text);arr=Array.isArray(j)?j:(j.pronunciations||j.dictionary||[]);arr=arr.map(d=>({id:uid(),from:d.from||d.written||d.word||'',to:d.to||d.spoken||d.pronunciation||''}));}catch{arr=text.split(/\n/).map(x=>x.trim()).filter(x=>x&&!x.startsWith('#')).map(line=>{const m=line.split(/\s*(?:->|=>|=|,|\t)\s*/);return{id:uid(),from:m[0]||'',to:m.slice(1).join(' ')||''}}).filter(d=>d.from&&d.to)}if(arr.length)state.dictionary=arr;}
function applyGuide(text){const rows=text.split(/\n/);for(const row of rows){const m=row.match(/^\s*([A-Za-z][A-Za-z0-9 '\-]{1,30})\s*[:|]\s*(.+)$/);if(!m)continue;const c=ensureChar(m[1].trim());const body=m[2];const v=VOICES.find(([id,label])=>body.toLowerCase().includes(id.toLowerCase())||body.toLowerCase().includes(label.split(' · ')[0].toLowerCase()));if(v)c.voice=v[0];const sm=body.match(/speed\s*[:=]?\s*([\d.]+)/i);if(sm)c.speed=clamp(sm[1],.5,1.6);const pm=body.match(/pitch\s*[:=]?\s*([+\-]?[\d.]+)/i);if(pm)c.pitch=clamp(pm[1],-6,6);for(const tone of TONES)if(body.toLowerCase().includes(tone))c.tone=tone;for(const em of Object.keys(EMOTIONS))if(body.toLowerCase().includes(em))c.emotion=em;}}

const SAY='said|asked|whispered|replied|answered|murmured|shouted|yelled|cried|called|growled|snapped|hissed|added|continued|muttered|rasped';
function parseText(text){const paras=String(text||'').replace(/\r/g,'').split(/\n\s*\n+/).map(s=>s.trim()).filter(Boolean);const out=[];let previous='Unknown';for(const p of paras){const explicit=p.match(/^([A-Z][A-Z0-9 _'’\-]{1,40}):\s*([\s\S]+)$/);if(explicit){const sp=titleCase(explicit[1]);ensureChar(sp);out.push(mkLine(explicit[2],sp,sp==='Narrator'?'narration':'dialogue',1));previous=sp;continue;}const parts=[];const re=/[“"]([^”"]+)[”"]/g;let last=0,m;while((m=re.exec(p))){if(m.index>last)parts.push({text:p.slice(last,m.index).trim(),quote:false});parts.push({text:m[1].trim(),quote:true});last=re.lastIndex}if(last<p.length)parts.push({text:p.slice(last).trim(),quote:false});if(!parts.some(x=>x.quote)){out.push(...splitNarration(p).map(x=>mkLine(x,'Narrator','narration',1)));continue;}for(let i=0;i<parts.length;i++){const a=parts[i];if(!a.text)continue;if(!a.quote){splitNarration(a.text).forEach(x=>out.push(mkLine(x,'Narrator','narration',1)));continue;}const ctx=`${parts[i-1]?.text||''} ${parts[i+1]?.text||''}`;let sp='Unknown',conf=0;for(const c of state.characters){const er=c.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(new RegExp(`\\b${er}\\b\\s+(?:${SAY})\\b|(?:${SAY})\\s+\\b${er}\\b`,'i').test(ctx)){sp=c.name;conf=.95;break}}if(sp==='Unknown'&&previous!=='Unknown'){sp=previous;conf=.3}out.push(mkLine(a.text,sp,'dialogue',conf));previous=sp;}}return out;}
function splitNarration(s){const max=420;if(s.length<=max)return[s];const sentences=s.match(/[^.!?…]+[.!?…]+|[^.!?…]+$/g)||[s];const out=[];let cur='';for(const q of sentences){if((cur+' '+q).trim().length>max&&cur){out.push(cur.trim());cur=q}else cur=(cur+' '+q).trim()}if(cur)out.push(cur);return out;}
function mkLine(text,speaker,type,confidence){return{id:uid(),text:text.trim(),speaker,type,confidence,emotion:'neutral',pause:null,note:'',generated:false};}
function titleCase(s){return s.trim().toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}

let kokoroWorker=null;
let kokoroWorkerSeq=0;
let kokoroWorkerPending=new Map();
let kokoroWorkerReady=false;
let kokoroWorkerConfigKey='';
let voicePreviewBusy=false;
function setEngineProgress(msg,busy=false){const e=byId('engineProgress');if(e)e.innerHTML=(busy?'<span class="spinner"></span>':'')+esc(msg||'');if(msg)setStatus(msg);}
function setVoiceBusy(on,msg=''){voicePreviewBusy=!!on;document.querySelectorAll('.quickPreview,.previewOne,#previewVoice,#loadK').forEach(b=>b.disabled=!!on);const c=byId('cancelK');if(c)c.disabled=!on&&!kokoroWorker;if(msg)setEngineProgress(msg,on);}
function rejectWorkerPending(reason){for(const [,p] of kokoroWorkerPending){try{p.reject(new Error(reason))}catch{}}kokoroWorkerPending.clear();}
function stopKokoroWorker(reason='Voice engine canceled'){if(kokoroWorker){try{kokoroWorker.terminate()}catch{}}kokoroWorker=null;kokoroWorkerReady=false;kokoro=null;kokoroLoading=null;rejectWorkerPending(reason);setVoiceBusy(false);setEngineProgress(reason,false);}
function ensureKokoroWorker(){if(kokoroWorker)return kokoroWorker;const w=new Worker('/kokoro-worker.js?v=070',{type:'module'});kokoroWorker=w;w.onmessage=(ev)=>{const m=ev.data||{};if(m.type==='progress'){const d=m.data||{};let text='Loading Kokoro model…';if(d.status==='progress'&&Number.isFinite(d.progress))text=`Loading Kokoro model · ${Math.round(d.progress)}%`;else if(d.file)text=`Loading ${d.file}`;setEngineProgress(text,true);return;}if(m.type==='status'){setEngineProgress(m.message||'Voice engine working…',m.busy!==false);return;}const p=kokoroWorkerPending.get(m.id);if(!p)return;kokoroWorkerPending.delete(m.id);if(m.ok)p.resolve(m);else p.reject(new Error(m.error||'Voice worker failed'));};w.onerror=(e)=>{console.error('Kokoro worker error',e);rejectWorkerPending(e.message||'Voice worker crashed');kokoroWorkerReady=false;kokoro=null;setVoiceBusy(false);setEngineProgress('Voice worker crashed · app still running',false);};return w;}
function kokoroWorkerCall(type,payload={}){const w=ensureKokoroWorker();const id='kw-'+(++kokoroWorkerSeq)+'-'+Date.now();return new Promise((resolve,reject)=>{kokoroWorkerPending.set(id,{resolve,reject});try{w.postMessage({id,type,...payload})}catch(e){kokoroWorkerPending.delete(id);reject(e)}});}
async function loadKokoro(){if(kokoro&&kokoroWorkerReady)return kokoro;if(kokoroLoading)return kokoroLoading;kokoroLoading=(async()=>{let device=state.settings.device;if(device==='auto')device=navigator.gpu?'webgpu':'wasm';let dtype;if(device==='webgpu')dtype=state.settings.memorySaver?'q4f16':(state.settings.dtype==='q4'?'q4f16':state.settings.dtype);else dtype=state.settings.memorySaver?'q4':state.settings.dtype;const cfg=`${device}:${dtype}`;if(kokoroWorkerReady&&kokoroWorkerConfigKey===cfg)return kokoro;setVoiceBusy(true,`Starting voice engine · ${device} ${dtype}`);const r=await kokoroWorkerCall('load',{model:KOKORO_MODEL,device,dtype});kokoroWorkerReady=true;kokoroWorkerConfigKey=`${r.device||device}:${r.dtype||dtype}`;kokoro={generate:async(text,opts={})=>{const g=await kokoroWorkerCall('generate',{text,voice:opts.voice,speed:opts.speed||1});return {toBlob:async()=>g.blob};},dispose:async()=>{try{await kokoroWorkerCall('dispose')}catch{}}};setVoiceBusy(false);setEngineProgress(`Voice engine ready · ${r.device||device} ${r.dtype||dtype}`,false);return kokoro;})();try{return await kokoroLoading}catch(e){console.error(e);stopKokoroWorker('Voice engine failed · '+(e?.message||e));throw e}finally{kokoroLoading=null}}
async function disposeKokoro(){stopKokoroWorker('Voice engine unloaded');}
